


import React from 'react';
import '../App.css';
import api from '../api'
import Header from './Header';
import axios from 'axios';
import Loading from 'react-fullscreen-loading';
import swal from 'sweetalert';
// import Web3 from 'web3';
// import asset from "../abis/Assets.json"
// import Modal from 'react-modal';
// import QRCode from "react-qr-code";
// import { ethers } from "ethers";
// import config from '../config'
// require('dotenv').config()

import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';


class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      account: "",
      selectedFile: null,
      assetName: "",
      price: "",
      description: "",
      tokenId: "",
      dataList: [],
      showModal: false,
      imageName: "",
      newModel: false,
      ethadd: "",
      transHash: "",
      soldstatus: "",
      visible: false,
      loader: false,
      ipfsHash: ""
    };
  }


  async componentDidMount() {
    await this.getAllData()

  }




  //List of all data in table;
  getAllData = async () => {
    axios.get(api.API_URL + 'getalldata').then((listdata) => {
      // console.log("getalldatalist", listdata.data.data)
      this.setState({ dataList: listdata.data.data, soldstatus: listdata.data.data.soldStatus })
    }).catch((errs) => {
      // console.log("alldata_api_catchblock",errs)
    })
  }

  render() {
    return (
      <>
        <Header />
        <div className="container">
          <div style={{ textAlign: "center", marginTop: "75px" }}>
            {this.state.loader ? (<Loading loading background="#ffffff00" loaderColor="#3498db" />) : (

              <div className="main-body">
                <div className="sellers-area">
                  <div className="seller-title">
                    <h3>Quick Links </h3>
                    <div className="col-sm-12">
                      <ul class="nav explore-menu">
                        <li class="nav-item">
                          <a class="nav-link" href="#abousUs">⚡ About Us</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#metaBrick">🧱 MetaBrick</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#theIdea">💡 The idea / FAQ</a>
                        </li>

                      </ul>
                    </div>
                  </div>
                </div>

                <div className="sellers-area explore-section" style={{ marginTop: "20px" }}>
                  <div className="seller-title">

                    <div id="aboutUs" className="seller-title">
                      <h3 >Strayed Vessels</h3>
                      <p>Welcome to the Strayed Vessels Collective, our flagship in the Metaverse. Strayed Vessels is a collaborative team with only a handful of artists, selected by the founders.  We intend to create as much art as possible, both physical and digital. </p>
                    </div>
                  </div>
                </div>

                <div id="metaBrick" className="sellers-area">
                  <div className="seller-title">
                    <h3 ><span>🧱</span> MetaBrick</h3>
                    <br />
                    A group of 8,888 MetaBricks were programmatically generated by a random combination of 56 traits (adding more). Each of these one of a kind MetaBricks thrive on the Ethereum blockchain in the form of ERC-721 Tokens. The MetaBricks acts as governance tokens, where holders will gain access to the community and a number of very exclusive benefits.
                  </div>
                </div>

                <div id="theIdea" className="sellers-area" >
                  <div className="seller-title">
                    <h3 ><span>💡</span> Goal, Vision, Roadmap, Team, FAQ</h3>
                    <br />
                    Will be listed soon
                  </div>
                </div>

              </div>


            )}
          </div>


        </div>
      </>
    )
  }
}




export default Home;